services:
  # --- DATABASE ---
  database:
    build:
      context: .
      dockerfile: tests/db.Dockerfile
    container_name: mairie360-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: core
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d core"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- TESTER ---
  tester:
    build: 
      context: .
      dockerfile: tests/test.Dockerfile
    container_name: mairie360-tester
    environment:
      - PGPASSWORD=password
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://database:5432/core
      - LIQUIBASE_COMMAND_USERNAME=postgres
      - LIQUIBASE_COMMAND_PASSWORD=password
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=changelog.xml
      - LIQUIBASE_COMMAND_DRIVER=org.postgresql.Driver
      # On pointe précisément là où sont tes fichiers (vu dans ton ls -la)
      - LIQUIBASE_SEARCH_PATH=/workspace/liquibase
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "
      echo '--- RUNNING MIGRATIONS ---' &&
      liquibase update &&
      
      echo '--- INSTALLING PGTAP ---' &&
      psql -h database -U postgres -d core -c 'CREATE EXTENSION IF NOT EXISTS pgtap;' &&
      
      echo '--- RUNNING TESTS ---' &&
      pg_prove -h database -U postgres -d core /workspace/tests/*.sql
      "
