networks:
  default:

services:
  # --- DATABASE ---
  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mairie360-db
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: core
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- LIQUIBASE ---
  liquibase:
    build:
      context: .
      dockerfile: liquibase/Dockerfile
    container_name: mairie360-liquibase
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://mairie360-db:5432/core
      - LIQUIBASE_COMMAND_USERNAME=postgres
      - LIQUIBASE_COMMAND_PASSWORD=password
      - LIQUIBASE_SEARCH_PATH=/migrations
    command: >
      --changelog-file=/changelog.xml
      update