-- Messagerie instantanée : type de conversation explicite, mentions et liens
-- métier. (Les pièces jointes de messages relèvent du module « files », non
-- prévu pour l'instant.)
--
-- Sécurité prod : les contraintes posées sur des tables préexistantes sont
-- ajoutées en NOT VALID — elles s'appliquent aux écritures futures sans faire
-- échouer la migration sur d'éventuelles données historiques non conformes.
-- La validation (VALIDATE CONSTRAINT) est une étape d'exploitation ultérieure,
-- après audit des données.

---
-- conversations : type explicite direct / groupe
---
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS kind VARCHAR(16);

-- Reprise : toute ligne existante reçoit une valeur (jamais NULL après ce pas).
UPDATE conversations
SET kind = CASE WHEN group_id IS NOT NULL THEN 'group' ELSE 'direct' END
WHERE kind IS NULL;

ALTER TABLE conversations ALTER COLUMN kind SET NOT NULL;

ALTER TABLE conversations DROP CONSTRAINT IF EXISTS chk_conversations_kind;
ALTER TABLE conversations ADD CONSTRAINT chk_conversations_kind
    CHECK (kind IN ('direct', 'group')) NOT VALID;

---
-- message_mentions
---
CREATE TABLE IF NOT EXISTS message_mentions (
    message_id BIGINT  NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (message_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_message_mentions_user ON message_mentions (user_id, message_id);

---
-- message_business_links : un message référence un objet métier
---
CREATE TABLE IF NOT EXISTS message_business_links (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT  NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,
    task_id    INTEGER REFERENCES tasks(id) ON DELETE CASCADE,
    event_id   INTEGER REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT chk_message_business_links_target
        CHECK (num_nonnulls(project_id, task_id, event_id) = 1)
);

-- Index de couverture des clés étrangères.
CREATE INDEX IF NOT EXISTS idx_mbl_message ON message_business_links (message_id);
CREATE INDEX IF NOT EXISTS idx_mbl_project ON message_business_links (project_id);
CREATE INDEX IF NOT EXISTS idx_mbl_task    ON message_business_links (task_id);
CREATE INDEX IF NOT EXISTS idx_mbl_event   ON message_business_links (event_id);

-- Anti-doublon : une même cible n'est liée qu'une fois au même message.
CREATE UNIQUE INDEX IF NOT EXISTS uq_mbl_message_project
    ON message_business_links (message_id, project_id) WHERE project_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_mbl_message_task
    ON message_business_links (message_id, task_id) WHERE task_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_mbl_message_event
    ON message_business_links (message_id, event_id) WHERE event_id IS NOT NULL;
