name: Database CD

on:
  workflow_dispatch:
  push:
    # branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  dev-release:
    uses: mairie360/CICD/.github/workflows/database_cd.yml@feat/mair-23-add-release-and-tag-creation-for-db
    with:
      job: "release"
      environment: "dev"
