name: Database CD

on:
  workflow_dispatch:
  push:
    # branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  dev-release:
    uses: mairie360/CICD/.github/workflows/database_cd.yml@feat/mair-23-add-release-and-tag-creation-for-db
    with:
      job: "release"
      environment: "dev"

  dev-deploy:
    needs: dev-release
    uses: mairie360/CICD/.github/workflows/database_cd.yml@feat/mair-23-add-release-and-tag-creation-for-db
    with:
      job: "deploy"
      environment: "dev"

  # staging-release:
  #   needs: dev-deploy
  #   uses: mairie360/CICD/.github/workflows/database_cd.yml@feat/mair-23-add-release-and-tag-creation-for-db
  #   with:
  #     job: "release"
  #     environment: "staging"

  # staging-deploy:
  #   needs: staging-release
  #   uses: mairie360/CICD/.github/workflows/database_cd.yml@feat/mair-23-add-release-and-tag-creation-for-db
  #   with:
  #     job: "deploy"
  #     environment: "staging"

  # prod-release:
  #   needs: staging-deploy
  #   uses: mairie360/CICD/.github/workflows/database_cd.yml@feat/mair-23-add-release-and-tag-creation-for-db
  #   with:
  #     job: "release"
  #     environment: "prod"

  # prod-deploy:
  #   needs: prod-release
  #   uses: mairie360/CICD/.github/workflows/database_cd.yml@feat/mair-23-add-release-and-tag-creation-for-db
  #   with:
  #     job: "deploy"
  #     environment: "prod"
