name: Database CI/CD

on:
  workflow_dispatch:
  push:

permissions:
  contents: write
  packages: write

jobs:
  Database-cicd:
    uses: mairie360/CICD/.github/workflows/database_cicd.yml@v3.1.1
    with:
      package_name: database
      cicd_version: v2.1.0
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      N8N_WEBHOOK_SECRET: ${{ secrets.N8N_WEBHOOK_SECRET }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
