name: Database CI/CD

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: write

jobs:
  call-database-cicd:
    uses: mairie360/CICD/.github/workflows/database_cicd.yml@1.4.0
    with:
      package_name: database
      cicd_version: 1.4.0
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
