name: Docker Build Temporary Manual

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-cicd:
    uses: mairie360/CICD/.github/workflows/docker_manual_build.yml@main
    with:
      package_name: database
