name: Docker Build Temporary Manual

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-cicd:
    uses: mairie360/CICD/.github/workflows/docker_manual.yml@3-feat-add-creation-of-package
    with:
      package_name: database
