name: Docker Build Temporary Manual

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-cicd:
    uses: mairie360/CICD/.github/actions/docker/docker_manual_build/action.yml@feat/mair-23-add-release-and-tag-creation-for-db
    with:
      package_name: database
