# name: Cleanup Temporary Docker Images

# on:
#   schedule:
#     - cron: '0 0 * * *' # Runs every day at midnight

# jobs:
#   cleanup:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Cleanup old images
#         uses: crazy-max/ghaction-github-docker-cleanup@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           keep-last: 7 # Keep images for the last 7 days
